version: 2.1
workflow:
    build:
        jobs:
            - build
jobs:
  build:
    docker:
        - image: cimg/node:14.10.1
    steps:
        - checkout
        - restore_cache:
           key:
             - npm-v1-dependencies-{{ checksum "yarn.lock" }}
        - run: yarn global add node-gyp && yarn install
        - save_cache:
           paths:
             - ./cache/yarn
           key:
             - npm-v1-dependencies-{{ checksum "yarn.lock" }}
